trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- bash: |
    echo "Environmental Valued"
  env:
   backendIP: '52.142.14.134'
   publicIP: '52.142.14.134'
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
- script: |
    npm run scan
  displayName: 'Static Code Analysis'

- script: |
    npm test
    npm run scan
  displayName: 'Execute Unit Test'

- script: |
    docker build -t mythicalmysfits:latest .
  displayName: 'Build Docker Image'
