trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Install Dependencies
  jobs:
  - job: Install
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
- stage: Unit Test
  jobs:
  - job: UnitTest
    steps:
    - script: npm test

