trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'Execute Unit Test'

- script: |
    docker build -t mythicalmysfits:latest .
  displayName: 'Build Docker Image'
